[package]
name = "azazel-coe5-update-signer"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
base64.workspace = true
ed25519-dalek.workspace = true
semver.workspace = true
serde.workspace = true
serde_json.workspace = true
